inputs:
  nickname:
    description: A name to refer to your name or any name.
    required: true
  banner1:
    description: can be a rel. path (relative to root) or URL
    required: false
    default: null
  banner2:
    description: can be a rel. path (relative to root) or URL
    required: false
    default: null
  gitname:
    description: Git name (for committing)
    required: true
  gitemail:
    description: Git email (for committing)
    required: true
  credit:
    description: Add this project repository URL at the end.
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - run: python $GITHUB_ACTION_PATH/lino_core
      shell: bash
      env:
        IPT__nickname: ${{ inputs.nickname }}
        IPT__banner1: ${{ inputs.banner1 }}
        IPT__banner2: ${{ inputs.banner2 }}
        IPT__credit: ${{ inputs.credit }}
        ACTION_REF: ${{ github.action_ref }}

    - run: |
        git config user.name "${{ inputs.gitname }}"
        git config user.email "${{ inputs.gitemail }}"
        git commit -am "Lineosaurus on $(date -u +'%Y %b %-d, %l:%M %p utc%:z')"
        git push
      shell: bash
