inputs:
  nickname:
    description: s
    required: true
  banner:
    description: s
    required: false
    default: null  # Note, `null` will be evaluated to an empty string by Python
  include_last_activity:
    description: s
    required: false
    default: false  # will be evaluated to a string 'false', not `True` / `False`
  gitname:
    description: Git name (for committing)
    required: true
  gitemail:
    description: Git email (for committing)
    required: true
  credit:
    description: Add a line to display credit to Lino at the end of the README
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - run: python $GITHUB_ACTION_PATH/lino_core
      shell: bash
      env:
        IPT__nickname: ${{ inputs.nickname }}
        IPT__banner: ${{ inputs.banner }}
        IPT__include_last_activity: ${{ inputs.include_last_activity }}
        IPT__credit: ${{ inputs.credit }}

    ## Save (committing)
    # - run: |
    #     git config user.name "${{ inputs.gitname }}"
    #     git config user.email "${{ inputs.gitemail }}"
    #     # git commit -am "Lineosaurus on $(date +'%Y %b %e, %l:%M %p')"
    #     git commit -am "Lineosaurus on $(date -u +'%Y %b %-d, %l:%M %p utc%:z')"
    #     git push
