inputs:
  gitname:
    description: Git name (for committing)
    required: true
  gitemail:
    description: Git email (for committing)
    required: true
  credit:
    description: Add a line to display credit to Lino at the end of the README
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - run: python $GITHUB_ACTION_PATH/lino_core
      shell: bash
      env:
        IPT__credit: ${{ inputs.credit }}

    ## Save (committing)
    - run: |
        git config user.name "${{ inputs.gitname }}"
        git config user.email "${{ inputs.gitemail }}"
        # git commit -am "Lineosaurus on $(date +'%Y %b %e, %l:%M %p')"
        git commit -am "Lineosaurus on $(date -u +'%Y %b %-d, %l:%M %p utc%:z')"
        git push
