name: Run tests

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: lineosaurus/lineosaurus@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          nickname: Hello Great
          banner: ./woow.jpg
          include_last_activity: true
          gitname: foo
          gitemail: bar
          credit: true
