name: Run tests

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

## Note: these tests will fail (because cant do the committing), but it doesn't mean the test itself failed, it's actually passed.
jobs:
  run:
    runs-on: ubuntu-latest
    # permissions: { contents: write }  # for committing  # NOTE: for testing purposes, comment out this line to not really make the commit.
    steps:
      - uses: lineosaurus/lineosaurus@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          nickname: Hello Great
          banner: ./woow.jpg
          include_last_activity: true
          gitname: foo
          gitemail: bar
          credit: true
  
  test_upBranch:  # using the update-branch (reminder: change the branch name below if needed)
    runs-on: ubuntu-latest
    # permissions: { contents: write }  # for committing  # NOTE: for testing purposes, comment out this line to not really make the commit.
    steps:
      - uses: lineosaurus/lineosaurus@up  # EDITME
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          nickname: Hello Great
          gitname: foo
          gitemail: bar
  
  test_default:  # just use the required args
    runs-on: ubuntu-latest
    # permissions: { contents: write }  # for committing  # NOTE: for testing purposes, comment out this line to not really make the commit.
    steps:
      - uses: lineosaurus/lineosaurus@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          nickname: Hello Great
          gitname: foo
          gitemail: bar

  run3:
    runs-on: ubuntu-latest
    # permissions: { contents: write }  # for committing  # NOTE: for testing purposes, comment out this line to not really make the commit.
    steps:
      - uses: lineosaurus/lineosaurus@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          nickname: Hello Great
          banner: ./woow.jpg
          include_last_activity: false
          gitname: foo
          gitemail: bar
          credit: false
  
  no_banner:
    runs-on: ubuntu-latest
    # permissions: { contents: write }  # for committing  # NOTE: for testing purposes, comment out this line to not really make the commit.
    steps:
      - uses: lineosaurus/lineosaurus@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          nickname: Hello Great
          include_last_activity: false
          gitname: foo
          gitemail: bar
          credit: true
